
DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS person;
CREATE TABLE person(
    person_id SERIAL,
	name varchar(20)not null,
	age integer ,
	email varchar,
	password varchar(50)not null,
	PRIMARY KEY(person_id)
);
-- INSERT INTO person(name,age,email,password) VALUES('Qollungirqi',27,'chansanuka@gmail.com','123');
-- INSERT INTO person(name,age,email,password) VALUES('Arridjakren',16,'terekeren@gmail.com','123');

ALTER TABLE person ADD COLUMN date_of_birth DATE;
ALTER TABLE person ADD COLUMN created_time TIMESTAMP;
ALTER TABLE person ADD COLUMN mood int;
ALTER TABLE person ADD COLUMN role varchar(100) not null;
SELECT * FROM person;
INSERT INTO person(name,age,email,password,role) VALUES('Timur',19,'tirukilum09@gmail.com','TERMITUS','ROLE_ADMIN');
INSERT INTO person(name,age,email,password,role) VALUES('Samka',18,'sepherhervar@gmail.com','Samka','ROLE_USER');

CREATE TABLE book(
   book_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   book_name varchar(50)not null,
   book_author varchar(50)not null,
   book_year int CHECK(book_year>1700),
   person_id integer REFERENCES person(person_id)ON DELETE SET NULL
);
--
-- INSERT INTO book(book_name,book_author,book_year,person_id)VALUES('Elrik from Melnibone','Michael Murkok',1988,1);
-- INSERT INTO book(book_name,book_author,book_year,person_id)VALUES('The Endless Book','Bastian Baltazar',1999,2);
-- INSERT INTO book(book_name,book_author,book_year,person_id)VALUES('Summer in heliconia','Bryan Oldiss',1956,3);
-- INSERT INTO book(book_name,book_author,book_year,person_id)VALUES('Elrik from Melnibone1','Michael Murkokf',1975,4);
-- INSERT INTO book(book_name,book_author,book_year,person_id)VALUES('Elrik from Melnibone2','Michael Murkok6',1944,3);
-- INSERT INTO book(book_name,book_author,book_year,person_id)VALUES('Elrik from Melnibone3','Michael Murkok4',1992,1);
SELECT * FROM book;

